// -----------------------------------------------------------------------------------
// 
// 
// 
// Generated by  6.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic(c,a,b){var d=$(this);this.go=function(e){b.find(".ws_list").css("transform","translate3d(0,0,0)").stop(true).animate({left:(e?-e+"00%":(/Safari/.test(navigator.userAgent)?"0%":0))},c.duration,"easeInOutExpo",function(){d.trigger("effectEnd")})}};// -----------------------------------------------------------------------------------
// 
// 
// 
// Generated by  6.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#slideshower-container1").slideshower({effect:"basic",prev:"",next:"",duration:15*100,delay:50*100,width:2000,height:625,autoPlay:true,autoPlayVideo:false,playPause:false,stopOnHover:false,loop:false,bullets:1,caption:true,captionEffect:"slide",controls:true,responsive:2,fullScreen:false,onBeforeStep:0,images:0});